name: kifuliiru_app
description: "Kifuliiru App for Kifuliiru learning, news and much more."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  introduction_screen: ^3.1.12
  #supabase_flutter: ^2.5.2
  audioplayers: ^0.20.1  # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
