name: kifuliiru_app
description: "Kifuliiru App for Kifuliiru learning, news and much more."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  introduction_screen: ^3.1.12
  #supabase_flutter: ^2.5.2
  audioplayers: ^5.2.1 # Check for the latest version
  smooth_page_indicator: ^1.0.0 # Check for the latest version on pub.dev
  flutter_svg: ^1.1.6
  card_swiper: ^2.0.4
  flutter_launcher_icons: ^0.13.1 # Make sure this version is up to date
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  flutter_tts: ^3.8.5
  share_plus: ^7.2.1
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  google_sign_in: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/database/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/kifuliiru.png"
