/* class Igambo {
  String? title;
  String? sobaanuro;
  String? sobaanuroYeKiswahili;
  String? sobaanuroYeKifaransa;
  String? sobaanuroYeKingereza;
  int? ndetoSobanuuro;
  String? kishushanyo;
  List<String>? holidesirwi;

  Igambo(
      {this.title,
      this.sobaanuro,
      this.sobaanuroYeKiswahili,
      this.sobaanuroYeKifaransa,
      this.sobaanuroYeKingereza,
      this.ndetoSobanuuro,
      this.kishushanyo,
      this.holidesirwi});

  Igambo.fromJson(Map<String, dynamic> json) {
    title = json['Title'];
    sobaanuro = json['Sobaanuro'];
    sobaanuroYeKiswahili = json['Sobaanuro ye Kiswahili'];
    sobaanuroYeKifaransa = json['Sobaanuro ye Kifaransa'];
    sobaanuroYeKingereza = json['Sobaanuro ye Kingereza'];
    ndetoSobanuuro = json['Ndeto_sobanuuro'];
    kishushanyo = json['Kishushanyo'];
    //holidesirwi = json['Holidesirwi'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Title'] = this.title;
    data['Sobaanuro'] = this.sobaanuro;
    data['Sobaanuro ye Kiswahili'] = this.sobaanuroYeKiswahili;
    data['Sobaanuro ye Kifaransa'] = this.sobaanuroYeKifaransa;
    data['Sobaanuro ye Kingereza'] = this.sobaanuroYeKingereza;
    data['Ndeto_sobanuuro'] = this.ndetoSobanuuro;
    data['Kishushanyo'] = this.kishushanyo;
    data['Holidesirwi'] = this.holidesirwi;
    return data;
  }
}

Igambo ig1 = Igambo(
  title: "Umundu",
  sobaanuro: "Umundu aliri mundu",
  holidesirwi: null,
  kishushanyo: "",
  ndetoSobanuuro: 1,
  sobaanuroYeKifaransa: "",
  sobaanuroYeKingereza: "",
  sobaanuroYeKiswahili: "",
);
Igambo ig2 = Igambo(
  title: "Umundu",
  sobaanuro: "Umundu aliri mundu",
  holidesirwi: null,
  kishushanyo: "",
  ndetoSobanuuro: 1,
  sobaanuroYeKifaransa: "",
  sobaanuroYeKingereza: "",
  sobaanuroYeKiswahili: "",
);

List<Igambo> listAmagambo = [ig1, ig2];
 */

class Autogenerated {
  List<Igambo>? items;

  Autogenerated({this.items});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['items'] != null) {
      items = <Igambo>[];
      json['items'].forEach((v) {
        items!.add(Igambo.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (items != null) {
      data['items'] = items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Igambo {
  String? sId;
  String? sOwner;
  String? sCreatedDate;
  String? sUpdatedDate;
  String? sobaanuroYeKiswahili;
  String? sobaanuro;
  String? title;
  String? sobaanuroYeKingereza;
  String? sobaanuroYeKifaransa;
  List<String>? holidesirwi;

  Igambo(
      {this.sId,
      this.sOwner,
      this.sCreatedDate,
      this.sUpdatedDate,
      this.sobaanuroYeKiswahili,
      this.sobaanuro,
      this.title,
      this.sobaanuroYeKingereza,
      this.sobaanuroYeKifaransa,
      this.holidesirwi});

  Igambo.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    sOwner = json['_owner'];
    sCreatedDate = json['_createdDate'];
    sUpdatedDate = json['_updatedDate'];
    sobaanuroYeKiswahili = json['sobaanuroYeKiswahili'];
    sobaanuro = json['sobaanuro'];
    title = json['title'];
    sobaanuroYeKingereza = json['sobaanuroYeKingereza'];
    sobaanuroYeKifaransa = json['sobaanuroYeKifaransa'];
    holidesirwi = json['holidesirwi']?.cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['_id'] = sId;
    data['_owner'] = sOwner;
    data['_createdDate'] = sCreatedDate;
    data['_updatedDate'] = sUpdatedDate;
    data['sobaanuroYeKiswahili'] = sobaanuroYeKiswahili;
    data['sobaanuro'] = sobaanuro;
    data['title'] = title;
    data['sobaanuroYeKingereza'] = sobaanuroYeKingereza;
    data['sobaanuroYeKifaransa'] = sobaanuroYeKifaransa;
    data['holidesirwi'] = holidesirwi;
    return data;
  }
}

Igambo ig1 = Igambo(
  title: "Umundu",
  sobaanuro: "Umundu aliri mundu",
  holidesirwi: null,
  sobaanuroYeKifaransa: "",
  sobaanuroYeKingereza: "",
  sobaanuroYeKiswahili: "",
);
Igambo ig2 = Igambo(
  title: "Umundu",
  sobaanuro: "Umundu aliri mundu",
  holidesirwi: null,
  sobaanuroYeKifaransa: "",
  sobaanuroYeKingereza: "",
  sobaanuroYeKiswahili: "",
);

List<Igambo> listAmagambo = [ig1, ig2];
