class Autogenerated {
  List<Igambo>? items;

  Autogenerated({this.items});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['items'] != null) {
      items = <Igambo>[];
      json['items'].forEach((v) {
        items!.add(Igambo.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (items != null) {
      data['items'] = items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Igambo {
  String? sId;
  String? sOwner;
  String? sCreatedDate;
  String? sUpdatedDate;
  String? sobaanuroYeKiswahili;
  String? sobaanuro;
  String? title;
  String? sobaanuroYeKingereza;
  String? sobaanuroYeKifaransa;
  List<String>? holidesirwi;

  Igambo(
      {this.sId,
      this.sOwner,
      this.sCreatedDate,
      this.sUpdatedDate,
      this.sobaanuroYeKiswahili,
      this.sobaanuro,
      this.title,
      this.sobaanuroYeKingereza,
      this.sobaanuroYeKifaransa,
      this.holidesirwi});

  Igambo.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    sOwner = json['_owner'];
    sCreatedDate = json['_createdDate'];
    sUpdatedDate = json['_updatedDate'];
    sobaanuroYeKiswahili = json['sobaanuroYeKiswahili'];
    sobaanuro = json['sobaanuro'];
    title = json['title'];
    sobaanuroYeKingereza = json['sobaanuroYeKingereza'];
    sobaanuroYeKifaransa = json['sobaanuroYeKifaransa'];
    holidesirwi = json['holidesirwi']?.cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['_id'] = sId;
    data['_owner'] = sOwner;
    data['_createdDate'] = sCreatedDate;
    data['_updatedDate'] = sUpdatedDate;
    data['sobaanuroYeKiswahili'] = sobaanuroYeKiswahili;
    data['sobaanuro'] = sobaanuro;
    data['title'] = title;
    data['sobaanuroYeKingereza'] = sobaanuroYeKingereza;
    data['sobaanuroYeKifaransa'] = sobaanuroYeKifaransa;
    data['holidesirwi'] = holidesirwi;
    return data;
  }
}

Igambo ig1 = Igambo(
  title: "Umundu",
  sobaanuro: "Umundu aliri mundu",
  holidesirwi: null,
  sobaanuroYeKifaransa: "",
  sobaanuroYeKingereza: "",
  sobaanuroYeKiswahili: "",
);
Igambo ig2 = Igambo(
  title: "Umundu",
  sobaanuro: "Umundu aliri mundu",
  holidesirwi: null,
  sobaanuroYeKifaransa: "",
  sobaanuroYeKingereza: "",
  sobaanuroYeKiswahili: "",
);

List<Igambo> listAmagambo = [ig1, ig2];
